### ISSUE TITLE
Vue compiler sfc

### ISSUE THREAD

**Issue by xhostcom** [excid3/jumpstart#138]
Hi it has a bug with @vue/compiler-sfc (needs it adding, according to console) , also  webpack-dev-server not running right?

"export 'createBlock' (imported as '_createBlock') was not found in 'vue'"
Output of cmd

$ bin/webpack-dev-server
is below
warning ../../package.json: No license field                                   
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /home/anton/IProjects/myapp/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: Hash: 0f85c6b0b492a67b92ca
Version: webpack 4.46.0
Time: 2269ms
Built at: 17/07/2021 10:34:08
                                     Asset       Size       Chunks                         Chunk Names
    js/application-cf54230636ba51ee995b.js    855 KiB  application  [emitted] [immutable]  application
js/application-cf54230636ba51ee995b.js.map    891 KiB  application  [emitted] [dev]        application
      js/hello_vue-4cdfdbb7328c4f9d465a.js    653 KiB    hello_vue  [emitted] [immutable]  hello_vue
  js/hello_vue-4cdfdbb7328c4f9d465a.js.map    749 KiB    hello_vue  [emitted] [dev]        hello_vue
                             manifest.json  689 bytes               [emitted]              

ERROR in ./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true (./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--15-0!./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true) 9:24-36
"export 'createBlock' (imported as '_createBlock') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/anton/IProjects/myapp/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)

ERROR in ./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true (./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--15-0!./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true) 10:4-16
"export 'createVNode' (imported as '_createVNode') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/anton/IProjects/myapp/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)

ERROR in ./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true (./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--15-0!./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true) 9:10-20
"export 'openBlock' (imported as '_openBlock') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/anton/IProjects/myapp/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)

ERROR in ./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true (./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--15-0!./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true) 6:0-11
"export 'popScopeId' (imported as '_popScopeId') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/anton/IProjects/myapp/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)

ERROR in ./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true (./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--15-0!./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true) 4:0-12
"export 'pushScopeId' (imported as '_pushScopeId') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/anton/IProjects/myapp/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)

ERROR in ./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true (./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--15-0!./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true) 10:28-44
"export 'toDisplayString' (imported as '_toDisplayString') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/anton/IProjects/myapp/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)

ERROR in ./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true (./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--15-0!./app/javascript/app.vue?vue&type=template&id=6fb8108a&scoped=true) 2:29-41
"export 'withScopeId' (imported as '_withScopeId') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/home/anton/IProjects/myapp/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/anton/IProjects/myapp/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/anton/IProjects/myapp/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/anton/IProjects/myapp/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/home/anton/IProjects/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
ℹ ｢wdm｣: Failed to compile.

Bug?

**Comment by excid3** [comment]
Jumpstart doesn't use Vue, so this is out of scope for what we support.

**Comment by xhostcom** [comment]
Ok don't know how it got in there, I just generated another app  and
it doesnt have Vue! Thanks
