### ISSUE TITLE
NameError: uninitialized constant ActiveSupport::BasicObject

### ISSUE THREAD

**Issue by ohaddahan** [excid3/jumpstart#86]
Error after saving the configuration.

```

17:32:40 web.1     | Started GET "/" for ::1 at 2019-06-29 17:32:40 +0300
17:32:40 web.1     | Processing by StaticController#index as HTML
17:32:40 web.1     |   Rendering static/index.html.erb within layouts/application
17:32:40 web.1     |   Rendered static/index.html.erb within layouts/application (Duration: 1.8ms | Allocations: 368)
17:32:44 web.1     |   Rendered shared/_favicons.html.erb (Duration: 17.5ms | Allocations: 8484)
17:32:44 web.1     |   Rendered shared/_payments_dependencies.html.erb (Duration: 2.2ms | Allocations: 1831)
17:32:44 web.1     |   Rendered shared/_flash.html.erb (Duration: 0.8ms | Allocations: 195)
17:32:44 web.1     |   Rendered shared/_left_nav.html.erb (Duration: 0.5ms | Allocations: 92)
17:32:44 web.1     |   Announcement Load (1.3ms)  SELECT "announcements".* FROM "announcements" ORDER BY "announcements"."published_at" DESC LIMIT $1  [["LIMIT", 1]]
17:32:44 web.1     |   ↳ app/helpers/announcements_helper.rb:19:in `unread_announcements_class'
17:32:44 web.1     |   Rendered shared/_right_nav.html.erb (Duration: 11.9ms | Allocations: 2390)
17:32:44 web.1     |   Rendered shared/_navbar.html.erb (Duration: 18.6ms | Allocations: 5352)
17:32:44 web.1     |   Rendered shared/_footer.html.erb (Duration: 6.0ms | Allocations: 2808)
17:32:44 web.1     | Completed 200 OK in 3720ms (Views: 3698.9ms | ActiveRecord: 3.4ms | Allocations: 2336599)
17:32:44 web.1     | 
17:32:44 web.1     | 
17:32:49 web.1     | Started GET "/jumpstart" for ::1 at 2019-06-29 17:32:49 +0300
17:32:49 web.1     | Processing by Jumpstart::AdminController#show as HTML
17:32:49 web.1     |   Rendering lib/jumpstart/app/views/jumpstart/admin/show.html.erb within layouts/jumpstart/application
17:32:49 web.1     |   Rendered lib/jumpstart/app/views/jumpstart/admin/_payments.html.erb (Duration: 1.7ms | Allocations: 120)
17:32:49 web.1     |   Rendered lib/jumpstart/app/views/jumpstart/admin/show.html.erb within layouts/jumpstart/application (Duration: 8.7ms | Allocations: 2192)
17:32:49 web.1     | Completed 200 OK in 16ms (Views: 13.3ms | ActiveRecord: 0.0ms | Allocations: 5301)
17:32:49 web.1     | 
17:32:49 web.1     | 
17:32:51 web.1     | Started POST "/jumpstart/config" for ::1 at 2019-06-29 17:32:51 +0300
17:32:51 web.1     | Processing by Jumpstart::ConfigsController#create as JS
17:32:51 web.1     |   Parameters: {"authenticity_token"=>"WXnkzfhlhWcrruO4ynYKUYaIExjUzYh3INRRSsZz2WLK26QKeBXtJ0SS4WbNYLTlxp/+aGy7XOFL7NdAMdmllw==", "jumpstart_configuration"=>{"application_name"=>"[FILTERED]", "business_name"=>"[FILTERED]", "business_address"=>"2145 Hamilton Avenue San Jose, California 95125\n", "support_email"=>"[FILTERED]", "background_job_processor"=>"delayed_job", "email_provider"=>"[FILTERED]", "domain"=>"ebay-repricer.com", "default_from_email"=>"[FILTERED]", "payment_processors"=>["paypal"]}, "button"=>""}
17:32:51 web.1     | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
17:32:51 web.1     | Using rake 12.3.2
17:32:51 web.1     | Using concurrent-ruby 1.1.5
17:32:51 web.1     | Using i18n 1.6.0
17:32:51 web.1     | Using minitest 5.11.3
17:32:51 web.1     | Using thread_safe 0.3.6
17:32:51 web.1     | Using tzinfo 1.2.5
17:32:51 web.1     | Using zeitwerk 2.1.6
17:32:51 web.1     | Using activesupport 6.0.0.rc1
17:32:51 web.1     | Using builder 3.2.3
17:32:51 web.1     | Using erubi 1.8.0
17:32:51 web.1     | Using mini_portile2 2.4.0
17:32:51 web.1     | Using nokogiri 1.10.3
17:32:51 web.1     | Using rails-dom-testing 2.0.3
17:32:51 web.1     | Using crass 1.0.4
17:32:51 web.1     | Using loofah 2.2.3
17:32:51 web.1     | Using rails-html-sanitizer 1.0.4
17:32:51 web.1     | Using actionview 6.0.0.rc1
17:32:51 web.1     | Using rack 2.0.7
17:32:51 web.1     | Using rack-test 1.1.0
17:32:51 web.1     | Using actionpack 6.0.0.rc1
17:32:51 web.1     | Using nio4r 2.3.1
17:32:51 web.1     | Using websocket-extensions 0.1.4
17:32:51 web.1     | Using websocket-driver 0.7.1
17:32:51 web.1     | Using actioncable 6.0.0.rc1
17:32:51 web.1     | Using globalid 0.4.2
17:32:51 web.1     | Using activejob 6.0.0.rc1
17:32:51 web.1     | Using activemodel 6.0.0.rc1
17:32:51 web.1     | Using activerecord 6.0.0.rc1
17:32:51 web.1     | Using mimemagic 0.3.3
17:32:51 web.1     | Using marcel 0.3.3
17:32:51 web.1     | Using activestorage 6.0.0.rc1
17:32:51 web.1     | Using mini_mime 1.0.1
17:32:51 web.1     | Using mail 2.7.1
17:32:51 web.1     | Using actionmailbox 6.0.0.rc1
17:32:51 web.1     | Using actionmailer 6.0.0.rc1
17:32:51 web.1     | Using actiontext 6.0.0.rc1
17:32:51 web.1     | Using public_suffix 3.1.0
17:32:51 web.1     | Using addressable 2.6.0
17:32:51 web.1     | Using execjs 2.7.0
17:32:51 web.1     | Using autoprefixer-rails 9.6.0
17:32:51 web.1     | Using method_source 0.9.2
17:32:51 web.1     | Using thor 0.20.3
17:32:51 web.1     | Using railties 6.0.0.rc1
17:32:51 web.1     | Using momentjs-rails 2.20.1
17:32:51 web.1     | Using datetime_picker_rails 0.0.7
17:32:51 web.1     | Using jquery-rails 4.3.5
17:32:51 web.1     | Using kaminari-core 1.1.1
17:32:51 web.1     | Using kaminari-actionview 1.1.1
17:32:51 web.1     | Using kaminari-activerecord 1.1.1
17:32:51 web.1     | Using kaminari 1.1.1
17:32:51 web.1     | Using ffi 1.11.1
17:32:51 web.1     | Using sassc 2.0.1
17:32:51 web.1     | Using sprockets 3.7.2
17:32:51 web.1     | Using sprockets-rails 3.2.1
17:32:51 web.1     | Using tilt 2.0.9
17:32:51 web.1     | Using sassc-rails 2.1.1
17:32:51 web.1     | Using selectize-rails 0.12.6
17:32:51 web.1     | Using administrate 0.11.0 from https://github.com/excid3/administrate.git (at jumpstart@66c6d33)
17:32:51 web.1     | Using annotate 2.7.5
17:32:51 web.1     | Using encryptor 3.0.0
17:32:51 web.1     | Using attr_encrypted 3.1.0
17:32:51 web.1     | Using bcrypt 3.1.13
17:32:51 web.1     | Using bindex 0.7.0
17:32:51 web.1     | Using msgpack 1.2.10
17:32:51 web.1     | Using bootsnap 1.4.4
17:32:51 web.1     | Using braintree 2.97.0
17:32:51 web.1     | Using brakeman 4.5.1
17:32:51 web.1     | Using bundler 1.17.3
17:32:51 web.1     | Using bundler-audit 0.6.1
17:32:51 web.1     | Using byebug 11.0.1
17:32:51 web.1     | Using regexp_parser 1.5.1
17:32:51 web.1     | Using xpath 3.2.0
17:32:51 web.1     | Using capybara 3.24.0
17:32:51 web.1     | Using childprocess 1.0.1
17:32:51 web.1     | Using chronic 0.10.2
17:32:51 web.1     | Using coderay 1.1.2
17:32:51 web.1     | Using daemons 1.3.1
17:32:51 web.1     | Using delayed_job 2.0.6
17:32:51 web.1     | Using orm_adapter 0.5.0
17:32:51 web.1     | Using responders 2.4.1
17:32:51 web.1     | Using warden 1.2.8
17:32:51 web.1     | Using devise 4.6.2
17:32:51 web.1     | Using devise_invitable 2.0.1
17:32:51 web.1     | Using devise_masquerade 0.6.5
17:32:51 web.1     | Using hashie 3.6.0
17:32:51 web.1     | Using mini_magick 4.9.3
17:32:51 web.1     | Using ruby-vips 2.0.14
17:32:51 web.1     | Using image_processing 1.9.0
17:32:51 web.1     | Using inline_svg 1.5.2
17:32:51 web.1     | Using jbuilder 2.9.1
17:32:51 web.1     | Using rails 6.0.0.rc1
17:32:51 web.1     | Using jumpstart 0.1.0 from source at `lib/jumpstart`
17:32:51 web.1     | Using launchy 2.4.3
17:32:51 web.1     | Using letter_opener 1.7.0
17:32:51 web.1     | Using letter_opener_web 1.3.4
17:32:51 web.1     | Using rb-fsevent 0.10.3
17:32:51 web.1     | Using rb-inotify 0.10.0
17:32:51 web.1     | Using ruby_dep 1.5.0
17:32:51 web.1     | Using listen 3.1.5
17:32:51 web.1     | Using local_time 2.1.0
17:32:51 web.1     | Using name_of_person 1.1.1
17:32:51 web.1     | Using omniauth 1.9.0
17:32:51 web.1     | Using pagy 3.3.0
17:32:51 web.1     | Using pay 1.0.0
17:32:51 web.1     | Using pdf-core 0.7.0
17:32:51 web.1     | Using pg 1.1.4
17:32:51 web.1     | Using ttfunk 1.5.1
17:32:51 web.1     | Using prawn 2.2.2
17:32:51 web.1     | Using prawn-table 0.2.2
17:32:51 web.1     | Using pry 0.12.2
17:32:51 web.1     | Using pry-rails 0.3.9
17:32:51 web.1     | Using puma 3.12.1
17:32:51 web.1     | Using rack-proxy 0.6.5
17:32:51 web.1     | Using receipts 0.2.2
17:32:51 web.1     | Using redis 4.1.2
17:32:51 web.1     | Using rubyzip 1.2.3
17:32:51 web.1     | Using sass-listen 4.0.0
17:32:51 web.1     | Using sass 3.7.4
17:32:51 web.1     | Using sass-rails 5.0.7
17:32:51 web.1     | Using selenium-webdriver 3.142.3
17:32:51 web.1     | Using spring 2.1.0
17:32:51 web.1     | Using spring-watcher-listen 2.0.1
17:32:51 web.1     | Using strong_migrations 0.4.0
17:32:51 web.1     | Using turbolinks-source 5.2.0
17:32:51 web.1     | Using turbolinks 5.2.0
17:32:51 web.1     | Using turbolinks_render 0.9.15
17:32:51 web.1     | Using web-console 4.0.0
17:32:51 web.1     | Using webdrivers 4.0.1
17:32:51 web.1     | Using webpacker 4.0.7
17:32:51 web.1     | Using whenever 1.0.0
17:32:51 web.1     | Bundle complete! 42 Gemfile dependencies, 130 gems now installed.
17:32:51 web.1     | Use `bundle info [gemname]` to see where a bundled gem is installed.
17:32:54 web.1     | rails aborted!
17:32:54 web.1     | NameError: uninitialized constant ActiveSupport::BasicObject
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/delayed_job-2.0.6/lib/delayed/message_sending.rb:2:in `<module:Delayed>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/delayed_job-2.0.6/lib/delayed/message_sending.rb:1:in `<main>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/delayed_job-2.0.6/lib/delayed_job.rb:3:in `<main>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
17:32:54 web.1     | /Users/ohaddahan/Projects/repricer/config/application.rb:7:in `<main>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
17:32:54 web.1     | /Users/ohaddahan/Projects/repricer/Rakefile:4:in `<main>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc1/lib/rails/command.rb:48:in `invoke'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<main>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
17:32:54 web.1     | /Users/ohaddahan/Projects/repricer/bin/rails:9:in `<top (required)>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
17:32:54 web.1     | /Users/ohaddahan/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
17:32:54 web.1     | /Users/ohaddahan/Projects/repricer/bin/spring:15:in `require'
17:32:54 web.1     | /Users/ohaddahan/Projects/repricer/bin/spring:15:in `<top (required)>'
17:32:54 web.1     | bin/rails:3:in `load'
17:32:54 web.1     | bin/rails:3:in `<main>'
17:32:54 web.1     | (See full trace by running task with --trace)
17:32:54 web.1     |   Rendering lib/jumpstart/app/views/jumpstart/configs/create.js.erb
17:32:54 web.1     |   Rendered lib/jumpstart/app/views/jumpstart/configs/create.js.erb (Duration: 0.1ms | Allocations: 4)
17:32:54 web.1     | Completed 200 OK in 3319ms (Views: 0.9ms | ActiveRecord: 0.0ms | Allocations: 3020)

```

**Comment by ohaddahan** [comment]
Fixed by deleting `Gemfile.lock` and adding manually:
`gem 'delayed_job_active_record'` and running bundle manually.
